sudo: required
services:
  - docker

language: c
compiler:
    - clang
    - gcc
env:
    - OS=el DIST=6 PACK=rpm
    - OS=el DIST=7 PACK=rpm
    - OS=fedora DIST=20 PACK=rpm
    - OS=fedora DIST=21 PACK=rpm
    - OS=fedora DIST=22 PACK=rpm
    - OS=fedora DIST=23 PACK=rpm
    - PACK=none

matrix:
    exclude:
        - compiler: clang
          env: PACK=rpm

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - docker pull tarantool/build:$OS$DIST

#install:
#  - uname -a
#  - lsb_release -c -s
#  - curl http://tarantool.org/dist/public.key | sudo apt-key add -
#  - echo "deb http://tarantool.org/dist/master/ubuntu/ `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
#  - sudo apt-get update > /dev/null
#  - sudo apt-get -q install tarantool tarantool-dev
#  - sudo apt-get -q install python-yaml

script:
  #- cmake . -DCMAKE_BUILD_TYPE=Debug
  #- make
  #- sudo make test
  - cd pack
  - sh pack.sh $PACK $OS $DIST
  #- mkdir -p out
  #- cp build.sh out/
  #- docker run -v `pwd`/out:/home/rpm/result tarantool/build:$OS$DIST sh /home/rpm/result/build.sh
  - ls -lia out/

notifications:
  irc:
    channels:
      - irc.freenode.net#tarantool
    on_success: change
    on_failure: always
  email: true
