language: c

compiler:
  - clang
  - gcc

before_install:
  - git submodule update --init --recursive

install:
  - uname -a
  - lsb_release -c -s
  - curl http://tarantool.org/dist/public.key | sudo apt-key add -
  - echo "deb http://tarantool.org/dist/master/ubuntu/ `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
  - sudo apt-get update > /dev/null
  - sudo apt-get -q install tarantool tarantool-dev
  - sudo apt-get -q install python-yaml

script:
  - cmake . -DCMAKE_BUILD_TYPE=Debug
  - make
  - sudo make test

notifications:
  irc:
    channels:
      - irc.freenode.net#tarantool
    on_success: change
    on_failure: always
  email: false
