sudo: required
services:
  - docker

language: c
compiler:
    - clang
    - gcc
env:
    global:
      - OUT_REPO=karcher/test-repo
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=20 PACK=rpm
      - OS=fedora DIST=21 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=ubuntu DIST=precise PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=ubuntu DIST=vivid PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=debian DIST=jessie PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=debian DIST=wheezy PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=debian DIST=stretch PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - PACK=none

matrix:
    exclude:
      - env: OS=el DIST=6 PACK=rpm
        compiler: clang
      - env: OS=el DIST=7 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=20 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=21 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=22 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=23 PACK=rpm
        compiler: clang
      - env: OS=ubuntu DIST=trusty PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=ubuntu DIST=precise PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=ubuntu DIST=vivid PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=debian DIST=jessie PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=debian DIST=wheezy PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=debian DIST=stretch PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - gem install package_cloud

install:
  - uname -a
  - lsb_release -c -s
  # uncomment this to disable packaging for failed tests
  #- curl http://tarantool.org/dist/public.key | sudo apt-key add -
  #- echo "deb http://tarantool.org/dist/master/ubuntu/ `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
  #- sudo apt-get update > /dev/null
  #- sudo apt-get -q install tarantool tarantool-dev
  #- sudo apt-get -q install python-yaml

script:
  #- cmake . -DCMAKE_BUILD_TYPE=Debug
  #- make
  #- sudo make test
  - cd build/pack
  - sh pack.sh $PACK $OS $DIST $TRAVIS_BRANCH $OUT_REPO $PROD $P_URI

notifications:
  irc:
    channels:
      - irc.freenode.net#tarantool
    on_success: change
    on_failure: always
  email: true
