sudo: required
services:
  - docker

language: c
compiler:
    - clang
    - gcc
env:
    global:
      - OUT_REPO=tarantool/modules
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=20 PACK=rpm
      - OS=fedora DIST=21 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=ubuntu DIST=precise PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=ubuntu DIST=vivid PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=debian DIST=jessie PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=debian DIST=wheezy PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - OS=debian DIST=stretch PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
      - PACK=none

matrix:
    exclude:
      - env: OS=el DIST=6 PACK=rpm
        compiler: clang
      - env: OS=el DIST=7 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=20 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=21 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=22 PACK=rpm
        compiler: clang
      - env: OS=fedora DIST=23 PACK=rpm
        compiler: clang
      - env: OS=ubuntu DIST=trusty PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=ubuntu DIST=precise PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=ubuntu DIST=vivid PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=debian DIST=jessie PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=debian DIST=wheezy PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang
      - env: OS=debian DIST=stretch PACK=deb PROD=tarantool-c P_URI=https://github.com/tarantool/tarantool-c.git
        compiler: clang

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - gem install package_cloud

install:
  - uname -a
  - lsb_release -c -s

script:
  - bash test.sh $PACK
  - cd build/pack
  - bash pack.sh $PACK $OS $DIST $TRAVIS_BRANCH $OUT_REPO $PROD $P_URI

notifications:
  irc:
    channels:
      - irc.freenode.net#tarantool
    on_success: change
    on_failure: always
  email: true
